{% set name = "ffmpy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ffmpy-{{ version }}.tar.gz
  sha256: a173b8f42c7c669ff722df7fb31e1e870067713697f745224fa6e621b82f0004

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - ffmpeg
  run:
    - python >=3.6
    - ffmpeg

test:
  imports:
    - ffmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ch00k/ffmpy
  summary: A simple Python wrapper for ffmpeg
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattTriano
